export const TOGGLE_SIDEBAR = "ui/TOGGLE_SIDEBAR";
export const SET_SIDEBAR_STATE = "ui/SET_SIDEBAR_STATE";
export const TOGGLE_SIDEBAR_COLLAPSE = "ui/TOGGLE_SIDEBAR_COLLAPSE";
export const SET_SIDEBAR_COLLAPSED = "ui/SET_SIDEBAR_COLLAPSED";
